In [1]:
import os
from sklearn.model_selection import train_test_split



In [2]:
import os
import cv2
import numpy as np
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import img_to_array

def load_images(dir_path):
    
    X = []  # Liste des images
    Y = []  # Liste des labels correspondants

    # Récupération et tri des dossiers
    dossiers = sorted(os.listdir(dir_path))
    label_indices = {dossier: idx for idx, dossier in enumerate(dossiers)}  # Crée un dictionnaire pour mapper les noms de dossiers à un index

    # Parcourir chaque dossier dans le chemin spécifié
    for dossier in dossiers:
        dossier_chemin = os.path.join(dir_path, dossier)
        if os.path.isdir(dossier_chemin):

            # Parcourir chaque fichier image dans le dossier
            for fichier in os.listdir(dossier_chemin):
                fichier_chemin = os.path.join(dossier_chemin, fichier)
                # Vérifier si c'est un fichier image JPG
                if os.path.isfile(fichier_chemin) and fichier.lower().endswith('.jpg'):

                    # Charger l'image en niveaux de gris avec OpenCV
                    img = cv2.imread(fichier_chemin, cv2.IMREAD_GRAYSCALE)
                    if img is not None:

                        #ajouter edge detection ?
                        
                        # Redimensionne et convertit en tableau
                        img = cv2.resize(img, (64, 64))     # Redimensionne l'image
                        img = img_to_array(img)             # Convertit l'image en tableau NumPy
                        X.append(img)                       # Ajoute l'image
                        Y.append(label_indices[dossier])    # Ajoute l'index du label

    # Convertit les listes en tableaux NumPy
    X = np.array(X, dtype='float32') / 255.0  # Normalise des images
    Y = to_categorical(Y, num_classes=len(dossiers))  # Encode les labels en format one-hot

    return X, Y, label_indices


dir_path = 'asl_alphabet_train/asl_alphabet_train'

images, labels, label_indices = load_images(dir_path)

print("Number of images:", len(images))
print("Number of labels:", len(labels))
print("Label indices:", label_indices)


Number of images: 87000
Number of labels: 87000
Label indices: {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9, 'K': 10, 'L': 11, 'M': 12, 'N': 13, 'O': 14, 'P': 15, 'Q': 16, 'R': 17, 'S': 18, 'T': 19, 'U': 20, 'V': 21, 'W': 22, 'X': 23, 'Y': 24, 'Z': 25, 'del': 26, 'nothing': 27, 'space': 28}


In [3]:
print(images[0])
print(images[0].shape)

[[[0.10980392]
  [0.11372549]
  [0.12156863]
  ...
  [0.14901961]
  [0.14509805]
  [0.14117648]]

 [[0.12156863]
  [0.20784314]
  [0.18431373]
  ...
  [0.6862745 ]
  [0.7254902 ]
  [0.7058824 ]]

 [[0.11764706]
  [0.22352941]
  [0.21176471]
  ...
  [0.7137255 ]
  [0.7019608 ]
  [0.7058824 ]]

 ...

 [[0.13725491]
  [0.5411765 ]
  [0.54509807]
  ...
  [0.5647059 ]
  [0.54901963]
  [0.5411765 ]]

 [[0.13333334]
  [0.5411765 ]
  [0.54509807]
  ...
  [0.54901963]
  [0.54509807]
  [0.5372549 ]]

 [[0.14509805]
  [0.5372549 ]
  [0.54509807]
  ...
  [0.54901963]
  [0.5372549 ]
  [0.5176471 ]]]
(64, 64, 1)


In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("Y_train shape:", Y_train.shape)
print("X_test shape:", X_test.shape)
print("Y_test shape:", Y_test.shape)

print(X_train)



X_train shape: (69600, 64, 64, 1)
Y_train shape: (69600, 29)
X_test shape: (17400, 64, 64, 1)
Y_test shape: (17400, 29)
[[[[0.12156863]
   [0.10196079]
   [0.10980392]
   ...
   [0.10980392]
   [0.11764706]
   [0.12941177]]

  [[0.11372549]
   [0.04705882]
   [0.04313726]
   ...
   [0.19607843]
   [0.24705882]
   [0.23137255]]

  [[0.10980392]
   [0.07450981]
   [0.06666667]
   ...
   [0.23137255]
   [0.21568628]
   [0.21568628]]

  ...

  [[0.13333334]
   [0.5686275 ]
   [0.5647059 ]
   ...
   [0.8745098 ]
   [0.88235295]
   [0.9019608 ]]

  [[0.13333334]
   [0.5686275 ]
   [0.5686275 ]
   ...
   [0.8784314 ]
   [0.8862745 ]
   [0.89411765]]

  [[0.14509805]
   [0.5568628 ]
   [0.5647059 ]
   ...
   [0.8980392 ]
   [0.89411765]
   [0.8980392 ]]]


 [[[0.11764706]
   [0.13725491]
   [0.13725491]
   ...
   [0.12156863]
   [0.1254902 ]
   [0.14509805]]

  [[0.13333334]
   [0.4       ]
   [0.41960785]
   ...
   [0.2509804 ]
   [0.4745098 ]
   [0.48235294]]

  [[0.1254902 ]
   [0.34509805]

# Entrainement du modèle